#include "sfinae_test.hpp"
#include "enum_type_test.hpp"
#include "maybe_test.hpp"
#include "sequence_test.hpp"
#include "prelude_test.hpp"
#include "numeric_test.hpp"
#include "scientific_test.hpp"
#include "cyclic_test.hpp"
#include "c_utility_test.hpp"
#include "sm_test.hpp"
#include "string_test.hpp"
// #include "format_test.hpp"
#include "sort_test.hpp"
#include "parser_test.hpp"
